[tools]
"tuist" = "4.200.5"
"swiftlint" = "0.64.1"
"swiftformat" = "0.52.10"
"pnpm" = "10.34.4"
"node" = "24.18.0"
"git-cliff" = "2.13.1"

[plugins]
tuist = "https://github.com/asdf-community/asdf-tuist"
