[tools]
"tuist" = "4.191.6"
"swiftlint" = "0.63.2"
"swiftformat" = "0.52.10"
"pnpm" = "10.33.2"
"node" = "22.22.2"
"git-cliff" = "2.13.1"

[plugins]
tuist = "https://github.com/asdf-community/asdf-tuist"
