[tools]
"tuist" = "4.43.1"
"swiftlint" = "0.54.0"
"swiftformat" = "0.52.10"
"pnpm" = "10.5.2"
"node" = "22.14.0"
"git-cliff" = "2.4.0"

[plugins]
tuist = "https://github.com/asdf-community/asdf-tuist"
