[tools]
"tuist" = "4.200.5"
"swiftlint" = "0.64.1"
"swiftformat" = "0.61.1"
"pnpm" = "10.34.4"
"node" = "22.23.1"
"git-cliff" = "2.13.1"

[plugins]
tuist = "https://github.com/asdf-community/asdf-tuist"
