#!/bin/bash
# mise description="Builds the project using Swift Package Manager in Linux"
set -euo pipefail

docker run --rm \
    --volume "$MISE_PROJECT_ROOT:/package" \
    --workdir "/package" \
    swiftlang/swift:nightly-6.0-focal \
    /bin/bash -c \
    "swift build --product Command --build-path ./.build/linux"
