#!/bin/bash
# mise description="Builds the project using Swift Package Manager in Linux"
set -euo pipefail

if command -v podman &> /dev/null
then
    CONTAINER_RUNTIME="podman"
elif command -v docker &> /dev/null
then
    CONTAINER_RUNTIME="docker"
else
    echo "Neither podman nor docker is installed. Please install one of them to proceed."
    exit 1
fi

$CONTAINER_RUNTIME run --rm \
    --volume "$MISE_PROJECT_ROOT:/package" \
    --workdir "/package" \
    swiftlang/swift:nightly-6.0-focal \
    /bin/bash -c \
    "swift test --build-path ./.build/linux"
