name: Deploy
on:
  push:
    branches:
      - 'main'

concurrency:
  group: deploy-${{ github.head_ref }}
  cancel-in-progress: true
  
jobs:
  docs:
    name: Docs
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: jdx/mise-action@v2
        with:
          experimental: true
      - run: pnpm install
      - run: mise run docs:deploy