name: Docs

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

concurrency:
  group: docs-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: 'ubuntu-latest'
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: jdx/mise-action@v2
        with:
            experimental: true
      - run: pnpm install
      - run: mise run docs:build