name: Docs

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

concurrency:
  group: docs-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: 'ubuntu-latest'
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: jdx/mise-action@v2
        with:
            experimental: true
      - run: pnpm install
      - run: mise run docs:build